import React from "react";
import { COLORS } from "./colors";
import {
  AutoStories,
  BlockOutlined,
  CalendarMonth,
  EditNote,
  FeedOutlined,
  Security,
  Sms,
  ViewQuilt,
} from "@mui/icons-material";

export const footerTypography = [
  {
    title: "About Us",
    link_1: "Login",
    link_2: "Register",
    link_3: "Search",
    link_4: "Singlemuslim Men",
    link_5: "Singlemuslim Women",
  },
  {
    title: "News",
    link_1: "Umrah Winners",
    link_2: "Success Stories",
    link_3: "Reviews",
    link_4: "In The News",
    link_5: "Site News",
    link_6: "PR",
  },
  {
    title: "Our Standards",
    link_1: "Code of Conduct",
    link_2: "Privacy & Security",
    link_3: "Terms and Conditions",
  },

  {
    title: "Help",
    link_1: "Help and Support",
    link_2: "Contact Us",
    link_3: "Submit a Bug",
  },
];

export const menuItemData = [
  "WorldWide",
  "UK",
  "France",
  "Germany",
  "Europe",
  "USA",
  "Canda",
  "UAE",
  "Middle East",
  "Pakistan",
  "Indai",
  "Kenya",
  "other",
];
export const sliderSetting = {
  fade: true,
  infinite: true,
  speed: 500,
  slidesToShow: 1,
  pauseOnHover: false,
  slidesToScroll: 1,
  waitForAnimate: false,
  autoplay: true,
  autoplaySpeed: 4000,
  position: "relative",
};

export const videoPic = [
  {
    id: 1,
    img: "/assets/images/video_pic_1.jpg",
  },
  {
    id: 2,
    img: "/assets/images/video_pic_2.jpg",
  },
  {
    id: 3,
    img: "/assets/images/video_pic_3.jpg",
  },
  {
    id: 4,
    img: "/assets/images/video_pic_4.jpg",
  },
];
export const sliderData = [
  {
    img: "assets/images/slide-1.jpg",
  },
  {
    img: "assets/images/slide-2.jpg",
  },
  {
    img: "assets/images/slide-3.jpg",
  },
  {
    img: "assets/images/slide-4.jpg",
  },
];

export const settingData = [
  {
    title: "Account",
    icon: React.createElement(ViewQuilt),
    backgroundColor: COLORS.blue.main,
    textColor: COLORS.white.main,
    iconStyles: { fontSize: "60px", color: COLORS.blue.main },
  },
  {
    title: "Membership",
    icon: React.createElement(CalendarMonth),
    backgroundColor: COLORS.green.main,
    textColor: COLORS.white.main,
    iconStyles: { fontSize: "60px", color: COLORS.green.main },
  },
  {
    title: "Block User",
    icon: React.createElement(BlockOutlined),
    backgroundColor: COLORS.purple.main,
    textColor: COLORS.white.main,
    iconStyles: { fontSize: "60px", color: COLORS.purple.main },
  },
  {
    title: "Contact Us",
    icon: React.createElement(Sms),
    backgroundColor: COLORS.purple.dark,
    textColor: COLORS.white.main,
    iconStyles: { fontSize: "60px", color: COLORS.purple.dark },
  },
];
export const privacyData = [
  {
    title: "Success Stories",
    icon: React.createElement(AutoStories),
    backgroundColor: "transparent",
    textColor: COLORS.orange.main,
    iconStyles: { fontSize: "60px", color: COLORS.orange.main },
  },
  {
    title: "In The News",
    icon: React.createElement(FeedOutlined),
    backgroundColor: "transparent",
    textColor: COLORS.green.lightGreen,
    iconStyles: { fontSize: "60px", color: COLORS.green.lightGreen },
  },
  {
    title: "Term and Conditions",
    icon: React.createElement(EditNote),
    backgroundColor: "transparent",
    textColor: COLORS.primary.main,
    iconStyles: { fontSize: "60px", color: COLORS.primary.main },
  },
  {
    title: "Privacy and Security",
    icon: React.createElement(Security),
    backgroundColor: "transparent",
    textColor: COLORS.secondary.main,
    iconStyles: { fontSize: "60px", color: COLORS.secondary.main },
  },
];

export const userData = [
  {
    img: "https://randomuser.me/api/portraits/women/1.jpg",
    gender: "Female",
    profession: "Profession 1",
    location: "City 1, Country 1",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 1",
    age: 21,
    religon: "sunni",
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/2.jpg",
    gender: "Male",
    profession: "Profession 2",
    location: "City 2, Country 2",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 2",
    age: 22,
    rating: 4.2,
    id: 2,
  },
  {
    img: "https://randomuser.me/api/portraits/women/3.jpg",
    gender: "Female",
    profession: "Profession 3",
    location: "City 3, Country 3",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 3",
    age: 23,
    rating: 4.3,
    id: 3,
  },
  {
    img: "https://randomuser.me/api/portraits/men/4.jpg",
    gender: "Male",
    profession: "Profession 4",
    location: "City 4, Country 4",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 4",
    age: 24,
    rating: 4.4,
    id: 4,
  },
  {
    img: "https://randomuser.me/api/portraits/women/5.jpg",
    gender: "Female",
    profession: "Profession 5",
    location: "City 5, Country 5",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 5",
    age: 25,
    rating: 4.5,
    id: 5,
  },
  {
    img: "https://randomuser.me/api/portraits/men/6.jpg",
    gender: "Male",
    profession: "Profession 6",
    location: "City 6, Country 6",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 6",
    age: 26,
    rating: 4.6,
    id: 6,
  },
  {
    img: "https://randomuser.me/api/portraits/women/7.jpg",
    gender: "Female",
    profession: "Profession 7",
    location: "City 7, Country 7",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 7",
    age: 27,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/8.jpg",
    gender: "Male",
    profession: "Profession 8",
    location: "City 8, Country 8",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 8",
    age: 28,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/9.jpg",
    gender: "Female",
    profession: "Profession 9",
    location: "City 9, Country 9",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 9",
    age: 29,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/10.jpg",
    gender: "Male",
    profession: "Profession 10",
    location: "City 10, Country 10",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 10",
    age: 30,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/11.jpg",
    gender: "Female",
    profession: "Profession 11",
    location: "City 11, Country 11",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 11",
    age: 31,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    gender: "Male",
    profession: "Profession 12",
    location: "City 12, Country 12",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 12",
    age: 32,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/13.jpg",
    gender: "Female",
    profession: "Profession 13",
    location: "City 13, Country 13",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 13",
    age: 33,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/14.jpg",
    gender: "Male",
    profession: "Profession 14",
    location: "City 14, Country 14",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 14",
    age: 34,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/15.jpg",
    gender: "Female",
    profession: "Profession 15",
    location: "City 15, Country 15",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 15",
    age: 35,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/16.jpg",
    gender: "Male",
    profession: "Profession 16",
    location: "City 16, Country 16",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 16",
    age: 36,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/17.jpg",
    gender: "Female",
    profession: "Profession 17",
    location: "City 17, Country 17",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 17",
    age: 37,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/18.jpg",
    gender: "Male",
    profession: "Profession 18",
    location: "City 18, Country 18",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 18",
    age: 38,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/19.jpg",
    gender: "Female",
    profession: "Profession 19",
    location: "City 19, Country 19",
    countryflag: "https://flagcdn.com/w320/tu.png",
    name: "User 19",
    age: 39,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/20.jpg",
    gender: "Male",
    profession: "Profession 20",
    location: "City 20, Country 20",
    countryflag: "https://flagcdn.com/w320/uv.png",
    name: "User 20",
    age: 40,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/21.jpg",
    gender: "Female",
    profession: "Profession 21",
    location: "City 21, Country 21",
    countryflag: "https://flagcdn.com/w320/vw.png",
    name: "User 21",
    age: 41,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/22.jpg",
    gender: "Male",
    profession: "Profession 22",
    location: "City 22, Country 22",
    countryflag: "https://flagcdn.com/w320/wx.png",
    name: "User 22",
    age: 42,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/23.jpg",
    gender: "Female",
    profession: "Profession 23",
    location: "City 23, Country 23",
    countryflag: "https://flagcdn.com/w320/xy.png",
    name: "User 23",
    age: 43,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/24.jpg",
    gender: "Male",
    profession: "Profession 24",
    location: "City 24, Country 24",
    countryflag: "https://flagcdn.com/w320/yz.png",
    name: "User 24",
    age: 44,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/25.jpg",
    gender: "Female",
    profession: "Profession 25",
    location: "City 25, Country 25",
    countryflag: "https://flagcdn.com/w320/za.png",
    name: "User 25",
    age: 45,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/26.jpg",
    gender: "Male",
    profession: "Profession 26",
    location: "City 26, Country 26",
    countryflag: "https://flagcdn.com/w320/ab.png",
    name: "User 26",
    age: 46,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/27.jpg",
    gender: "Female",
    profession: "Profession 27",
    location: "City 27, Country 27",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 27",
    age: 47,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/28.jpg",
    gender: "Male",
    profession: "Profession 28",
    location: "City 28, Country 28",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 28",
    age: 48,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/29.jpg",
    gender: "Female",
    profession: "Profession 29",
    location: "City 29, Country 29",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 29",
    age: 49,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/30.jpg",
    gender: "Male",
    profession: "Profession 30",
    location: "City 30, Country 30",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 30",
    age: 20,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/31.jpg",
    gender: "Female",
    profession: "Profession 31",
    location: "City 31, Country 31",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 31",
    age: 21,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    gender: "Male",
    profession: "Profession 32",
    location: "City 32, Country 32",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 32",
    age: 22,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/33.jpg",
    gender: "Female",
    profession: "Profession 33",
    location: "City 33, Country 33",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 33",
    age: 23,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/34.jpg",
    gender: "Male",
    profession: "Profession 34",
    location: "City 34, Country 34",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 34",
    age: 24,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/35.jpg",
    gender: "Female",
    profession: "Profession 35",
    location: "City 35, Country 35",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 35",
    age: 25,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/36.jpg",
    gender: "Male",
    profession: "Profession 36",
    location: "City 36, Country 36",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 36",
    age: 26,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/37.jpg",
    gender: "Female",
    profession: "Profession 37",
    location: "City 37, Country 37",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 37",
    age: 27,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/38.jpg",
    gender: "Male",
    profession: "Profession 38",
    location: "City 38, Country 38",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 38",
    age: 28,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/39.jpg",
    gender: "Female",
    profession: "Profession 39",
    location: "City 39, Country 39",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 39",
    age: 29,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/40.jpg",
    gender: "Male",
    profession: "Profession 40",
    location: "City 40, Country 40",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 40",
    age: 30,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/41.jpg",
    gender: "Female",
    profession: "Profession 41",
    location: "City 41, Country 41",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 41",
    age: 31,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/42.jpg",
    gender: "Male",
    profession: "Profession 42",
    location: "City 42, Country 42",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 42",
    age: 32,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/43.jpg",
    gender: "Female",
    profession: "Profession 43",
    location: "City 43, Country 43",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 43",
    age: 33,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/44.jpg",
    gender: "Male",
    profession: "Profession 44",
    location: "City 44, Country 44",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 44",
    age: 34,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/45.jpg",
    gender: "Female",
    profession: "Profession 45",
    location: "City 45, Country 45",
    countryflag: "https://flagcdn.com/w320/tu.png",
    name: "User 45",
    age: 35,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/46.jpg",
    gender: "Male",
    profession: "Profession 46",
    location: "City 46, Country 46",
    countryflag: "https://flagcdn.com/w320/uv.png",
    name: "User 46",
    age: 36,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/47.jpg",
    gender: "Female",
    profession: "Profession 47",
    location: "City 47, Country 47",
    countryflag: "https://flagcdn.com/w320/vw.png",
    name: "User 47",
    age: 37,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/48.jpg",
    gender: "Male",
    profession: "Profession 48",
    location: "City 48, Country 48",
    countryflag: "https://flagcdn.com/w320/wx.png",
    name: "User 48",
    age: 38,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/49.jpg",
    gender: "Female",
    profession: "Profession 49",
    location: "City 49, Country 49",
    countryflag: "https://flagcdn.com/w320/xy.png",
    name: "User 49",
    age: 39,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/50.jpg",
    gender: "Male",
    profession: "Profession 50",
    location: "City 50, Country 50",
    countryflag: "https://flagcdn.com/w320/yz.png",
    name: "User 50",
    age: 40,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/51.jpg",
    gender: "Female",
    profession: "Profession 51",
    location: "City 51, Country 51",
    countryflag: "https://flagcdn.com/w320/za.png",
    name: "User 51",
    age: 41,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/52.jpg",
    gender: "Male",
    profession: "Profession 52",
    location: "City 52, Country 52",
    countryflag: "https://flagcdn.com/w320/ab.png",
    name: "User 52",
    age: 42,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/53.jpg",
    gender: "Female",
    profession: "Profession 53",
    location: "City 53, Country 53",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 53",
    age: 43,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/54.jpg",
    gender: "Male",
    profession: "Profession 54",
    location: "City 54, Country 54",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 54",
    age: 44,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/55.jpg",
    gender: "Female",
    profession: "Profession 55",
    location: "City 55, Country 55",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 55",
    age: 45,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/56.jpg",
    gender: "Male",
    profession: "Profession 56",
    location: "City 56, Country 56",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 56",
    age: 46,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/57.jpg",
    gender: "Female",
    profession: "Profession 57",
    location: "City 57, Country 57",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 57",
    age: 47,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/58.jpg",
    gender: "Male",
    profession: "Profession 58",
    location: "City 58, Country 58",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 58",
    age: 48,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/59.jpg",
    gender: "Female",
    profession: "Profession 59",
    location: "City 59, Country 59",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 59",
    age: 49,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/60.jpg",
    gender: "Male",
    profession: "Profession 60",
    location: "City 60, Country 60",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 60",
    age: 20,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/61.jpg",
    gender: "Female",
    profession: "Profession 61",
    location: "City 61, Country 61",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 61",
    age: 21,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/62.jpg",
    gender: "Male",
    profession: "Profession 62",
    location: "City 62, Country 62",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 62",
    age: 22,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/63.jpg",
    gender: "Female",
    profession: "Profession 63",
    location: "City 63, Country 63",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 63",
    age: 23,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/64.jpg",
    gender: "Male",
    profession: "Profession 64",
    location: "City 64, Country 64",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 64",
    age: 24,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/65.jpg",
    gender: "Female",
    profession: "Profession 65",
    location: "City 65, Country 65",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 65",
    age: 25,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/66.jpg",
    gender: "Male",
    profession: "Profession 66",
    location: "City 66, Country 66",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 66",
    age: 26,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/67.jpg",
    gender: "Female",
    profession: "Profession 67",
    location: "City 67, Country 67",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 67",
    age: 27,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/68.jpg",
    gender: "Male",
    profession: "Profession 68",
    location: "City 68, Country 68",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 68",
    age: 28,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/69.jpg",
    gender: "Female",
    profession: "Profession 69",
    location: "City 69, Country 69",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 69",
    age: 29,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/70.jpg",
    gender: "Male",
    profession: "Profession 70",
    location: "City 70, Country 70",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 70",
    age: 30,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/71.jpg",
    gender: "Female",
    profession: "Profession 71",
    location: "City 71, Country 71",
    countryflag: "https://flagcdn.com/w320/tu.png",
    name: "User 71",
    age: 31,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/72.jpg",
    gender: "Male",
    profession: "Profession 72",
    location: "City 72, Country 72",
    countryflag: "https://flagcdn.com/w320/uv.png",
    name: "User 72",
    age: 32,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/73.jpg",
    gender: "Female",
    profession: "Profession 73",
    location: "City 73, Country 73",
    countryflag: "https://flagcdn.com/w320/vw.png",
    name: "User 73",
    age: 33,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/74.jpg",
    gender: "Male",
    profession: "Profession 74",
    location: "City 74, Country 74",
    countryflag: "https://flagcdn.com/w320/wx.png",
    name: "User 74",
    age: 34,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/75.jpg",
    gender: "Female",
    profession: "Profession 75",
    location: "City 75, Country 75",
    countryflag: "https://flagcdn.com/w320/xy.png",
    name: "User 75",
    age: 35,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/76.jpg",
    gender: "Male",
    profession: "Profession 76",
    location: "City 76, Country 76",
    countryflag: "https://flagcdn.com/w320/yz.png",
    name: "User 76",
    age: 36,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/77.jpg",
    gender: "Female",
    profession: "Profession 77",
    location: "City 77, Country 77",
    countryflag: "https://flagcdn.com/w320/za.png",
    name: "User 77",
    age: 37,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/78.jpg",
    gender: "Male",
    profession: "Profession 78",
    location: "City 78, Country 78",
    countryflag: "https://flagcdn.com/w320/ab.png",
    name: "User 78",
    age: 38,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/79.jpg",
    gender: "Female",
    profession: "Profession 79",
    location: "City 79, Country 79",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 79",
    age: 39,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/80.jpg",
    gender: "Male",
    profession: "Profession 80",
    location: "City 80, Country 80",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 80",
    age: 40,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/81.jpg",
    gender: "Female",
    profession: "Profession 81",
    location: "City 81, Country 81",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 81",
    age: 41,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/82.jpg",
    gender: "Male",
    profession: "Profession 82",
    location: "City 82, Country 82",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 82",
    age: 42,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/83.jpg",
    gender: "Female",
    profession: "Profession 83",
    location: "City 83, Country 83",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 83",
    age: 43,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/84.jpg",
    gender: "Male",
    profession: "Profession 84",
    location: "City 84, Country 84",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 84",
    age: 44,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/85.jpg",
    gender: "Female",
    profession: "Profession 85",
    location: "City 85, Country 85",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 85",
    age: 45,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/86.jpg",
    gender: "Male",
    profession: "Profession 86",
    location: "City 86, Country 86",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 86",
    age: 46,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/87.jpg",
    gender: "Female",
    profession: "Profession 87",
    location: "City 87, Country 87",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 87",
    age: 47,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/88.jpg",
    gender: "Male",
    profession: "Profession 88",
    location: "City 88, Country 88",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 88",
    age: 48,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/89.jpg",
    gender: "Female",
    profession: "Profession 89",
    location: "City 89, Country 89",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 89",
    age: 49,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/90.jpg",
    gender: "Male",
    profession: "Profession 90",
    location: "City 90, Country 90",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 90",
    age: 20,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/91.jpg",
    gender: "Female",
    profession: "Profession 91",
    location: "City 91, Country 91",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 91",
    age: 21,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/92.jpg",
    gender: "Male",
    profession: "Profession 92",
    location: "City 92, Country 92",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 92",
    age: 22,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/93.jpg",
    gender: "Female",
    profession: "Profession 93",
    location: "City 93, Country 93",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 93",
    age: 23,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/94.jpg",
    gender: "Male",
    profession: "Profession 94",
    location: "City 94, Country 94",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 94",
    age: 24,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/95.jpg",
    gender: "Female",
    profession: "Profession 95",
    location: "City 95, Country 95",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 95",
    age: 25,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/96.jpg",
    gender: "Male",
    profession: "Profession 96",
    location: "City 96, Country 96",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 96",
    age: 26,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/97.jpg",
    gender: "Female",
    profession: "Profession 97",
    location: "City 97, Country 97",
    countryflag: "https://flagcdn.com/w320/tu.png",
    name: "User 97",
    age: 27,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/98.jpg",
    gender: "Male",
    profession: "Profession 98",
    location: "City 98, Country 98",
    countryflag: "https://flagcdn.com/w320/uv.png",
    name: "User 98",
    age: 28,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/99.jpg",
    gender: "Female",
    profession: "Profession 99",
    location: "City 99, Country 99",
    countryflag: "https://flagcdn.com/w320/vw.png",
    name: "User 99",
    age: 29,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/0.jpg",
    gender: "Male",
    profession: "Profession 100",
    location: "City 100, Country 100",
    countryflag: "https://flagcdn.com/w320/wx.png",
    name: "User 100",
    age: 30,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/1.jpg",
    gender: "Female",
    profession: "Profession 101",
    location: "City 101, Country 101",
    countryflag: "https://flagcdn.com/w320/xy.png",
    name: "User 101",
    age: 31,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/2.jpg",
    gender: "Male",
    profession: "Profession 102",
    location: "City 102, Country 102",
    countryflag: "https://flagcdn.com/w320/yz.png",
    name: "User 102",
    age: 32,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/3.jpg",
    gender: "Female",
    profession: "Profession 103",
    location: "City 103, Country 103",
    countryflag: "https://flagcdn.com/w320/za.png",
    name: "User 103",
    age: 33,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/4.jpg",
    gender: "Male",
    profession: "Profession 104",
    location: "City 104, Country 104",
    countryflag: "https://flagcdn.com/w320/ab.png",
    name: "User 104",
    age: 34,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/5.jpg",
    gender: "Female",
    profession: "Profession 105",
    location: "City 105, Country 105",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 105",
    age: 35,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/6.jpg",
    gender: "Male",
    profession: "Profession 106",
    location: "City 106, Country 106",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 106",
    age: 36,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/7.jpg",
    gender: "Female",
    profession: "Profession 107",
    location: "City 107, Country 107",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 107",
    age: 37,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/8.jpg",
    gender: "Male",
    profession: "Profession 108",
    location: "City 108, Country 108",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 108",
    age: 38,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/9.jpg",
    gender: "Female",
    profession: "Profession 109",
    location: "City 109, Country 109",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 109",
    age: 39,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/10.jpg",
    gender: "Male",
    profession: "Profession 110",
    location: "City 110, Country 110",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 110",
    age: 40,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/11.jpg",
    gender: "Female",
    profession: "Profession 111",
    location: "City 111, Country 111",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 111",
    age: 41,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    gender: "Male",
    profession: "Profession 112",
    location: "City 112, Country 112",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 112",
    age: 42,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/13.jpg",
    gender: "Female",
    profession: "Profession 113",
    location: "City 113, Country 113",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 113",
    age: 43,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/14.jpg",
    gender: "Male",
    profession: "Profession 114",
    location: "City 114, Country 114",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 114",
    age: 44,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/15.jpg",
    gender: "Female",
    profession: "Profession 115",
    location: "City 115, Country 115",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 115",
    age: 45,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/16.jpg",
    gender: "Male",
    profession: "Profession 116",
    location: "City 116, Country 116",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 116",
    age: 46,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/17.jpg",
    gender: "Female",
    profession: "Profession 117",
    location: "City 117, Country 117",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 117",
    age: 47,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/18.jpg",
    gender: "Male",
    profession: "Profession 118",
    location: "City 118, Country 118",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 118",
    age: 48,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/19.jpg",
    gender: "Female",
    profession: "Profession 119",
    location: "City 119, Country 119",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 119",
    age: 49,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/20.jpg",
    gender: "Male",
    profession: "Profession 120",
    location: "City 120, Country 120",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 120",
    age: 20,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/21.jpg",
    gender: "Female",
    profession: "Profession 121",
    location: "City 121, Country 121",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 121",
    age: 21,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/22.jpg",
    gender: "Male",
    profession: "Profession 122",
    location: "City 122, Country 122",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 122",
    age: 22,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/23.jpg",
    gender: "Female",
    profession: "Profession 123",
    location: "City 123, Country 123",
    countryflag: "https://flagcdn.com/w320/tu.png",
    name: "User 123",
    age: 23,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/24.jpg",
    gender: "Male",
    profession: "Profession 124",
    location: "City 124, Country 124",
    countryflag: "https://flagcdn.com/w320/uv.png",
    name: "User 124",
    age: 24,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/25.jpg",
    gender: "Female",
    profession: "Profession 125",
    location: "City 125, Country 125",
    countryflag: "https://flagcdn.com/w320/vw.png",
    name: "User 125",
    age: 25,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/26.jpg",
    gender: "Male",
    profession: "Profession 126",
    location: "City 126, Country 126",
    countryflag: "https://flagcdn.com/w320/wx.png",
    name: "User 126",
    age: 26,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/27.jpg",
    gender: "Female",
    profession: "Profession 127",
    location: "City 127, Country 127",
    countryflag: "https://flagcdn.com/w320/xy.png",
    name: "User 127",
    age: 27,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/28.jpg",
    gender: "Male",
    profession: "Profession 128",
    location: "City 128, Country 128",
    countryflag: "https://flagcdn.com/w320/yz.png",
    name: "User 128",
    age: 28,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/29.jpg",
    gender: "Female",
    profession: "Profession 129",
    location: "City 129, Country 129",
    countryflag: "https://flagcdn.com/w320/za.png",
    name: "User 129",
    age: 29,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/30.jpg",
    gender: "Male",
    profession: "Profession 130",
    location: "City 130, Country 130",
    countryflag: "https://flagcdn.com/w320/ab.png",
    name: "User 130",
    age: 30,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/31.jpg",
    gender: "Female",
    profession: "Profession 131",
    location: "City 131, Country 131",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 131",
    age: 31,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    gender: "Male",
    profession: "Profession 132",
    location: "City 132, Country 132",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 132",
    age: 32,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/33.jpg",
    gender: "Female",
    profession: "Profession 133",
    location: "City 133, Country 133",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 133",
    age: 33,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/34.jpg",
    gender: "Male",
    profession: "Profession 134",
    location: "City 134, Country 134",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 134",
    age: 34,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/35.jpg",
    gender: "Female",
    profession: "Profession 135",
    location: "City 135, Country 135",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 135",
    age: 35,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/36.jpg",
    gender: "Male",
    profession: "Profession 136",
    location: "City 136, Country 136",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 136",
    age: 36,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/37.jpg",
    gender: "Female",
    profession: "Profession 137",
    location: "City 137, Country 137",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 137",
    age: 37,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/38.jpg",
    gender: "Male",
    profession: "Profession 138",
    location: "City 138, Country 138",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 138",
    age: 38,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/39.jpg",
    gender: "Female",
    profession: "Profession 139",
    location: "City 139, Country 139",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 139",
    age: 39,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/40.jpg",
    gender: "Male",
    profession: "Profession 140",
    location: "City 140, Country 140",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 140",
    age: 40,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/41.jpg",
    gender: "Female",
    profession: "Profession 141",
    location: "City 141, Country 141",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 141",
    age: 41,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/42.jpg",
    gender: "Male",
    profession: "Profession 142",
    location: "City 142, Country 142",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 142",
    age: 42,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/43.jpg",
    gender: "Female",
    profession: "Profession 143",
    location: "City 143, Country 143",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 143",
    age: 43,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/44.jpg",
    gender: "Male",
    profession: "Profession 144",
    location: "City 144, Country 144",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 144",
    age: 44,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/45.jpg",
    gender: "Female",
    profession: "Profession 145",
    location: "City 145, Country 145",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 145",
    age: 45,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/46.jpg",
    gender: "Male",
    profession: "Profession 146",
    location: "City 146, Country 146",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 146",
    age: 46,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/47.jpg",
    gender: "Female",
    profession: "Profession 147",
    location: "City 147, Country 147",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 147",
    age: 47,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/48.jpg",
    gender: "Male",
    profession: "Profession 148",
    location: "City 148, Country 148",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 148",
    age: 48,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/49.jpg",
    gender: "Female",
    profession: "Profession 149",
    location: "City 149, Country 149",
    countryflag: "https://flagcdn.com/w320/tu.png",
    name: "User 149",
    age: 49,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/50.jpg",
    gender: "Male",
    profession: "Profession 150",
    location: "City 150, Country 150",
    countryflag: "https://flagcdn.com/w320/uv.png",
    name: "User 150",
    age: 20,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/51.jpg",
    gender: "Female",
    profession: "Profession 151",
    location: "City 151, Country 151",
    countryflag: "https://flagcdn.com/w320/vw.png",
    name: "User 151",
    age: 21,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/52.jpg",
    gender: "Male",
    profession: "Profession 152",
    location: "City 152, Country 152",
    countryflag: "https://flagcdn.com/w320/wx.png",
    name: "User 152",
    age: 22,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/53.jpg",
    gender: "Female",
    profession: "Profession 153",
    location: "City 153, Country 153",
    countryflag: "https://flagcdn.com/w320/xy.png",
    name: "User 153",
    age: 23,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/54.jpg",
    gender: "Male",
    profession: "Profession 154",
    location: "City 154, Country 154",
    countryflag: "https://flagcdn.com/w320/yz.png",
    name: "User 154",
    age: 24,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/55.jpg",
    gender: "Female",
    profession: "Profession 155",
    location: "City 155, Country 155",
    countryflag: "https://flagcdn.com/w320/za.png",
    name: "User 155",
    age: 25,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/56.jpg",
    gender: "Male",
    profession: "Profession 156",
    location: "City 156, Country 156",
    countryflag: "https://flagcdn.com/w320/ab.png",
    name: "User 156",
    age: 26,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/57.jpg",
    gender: "Female",
    profession: "Profession 157",
    location: "City 157, Country 157",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 157",
    age: 27,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/58.jpg",
    gender: "Male",
    profession: "Profession 158",
    location: "City 158, Country 158",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 158",
    age: 28,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/59.jpg",
    gender: "Female",
    profession: "Profession 159",
    location: "City 159, Country 159",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 159",
    age: 29,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/60.jpg",
    gender: "Male",
    profession: "Profession 160",
    location: "City 160, Country 160",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 160",
    age: 30,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/61.jpg",
    gender: "Female",
    profession: "Profession 161",
    location: "City 161, Country 161",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 161",
    age: 31,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/62.jpg",
    gender: "Male",
    profession: "Profession 162",
    location: "City 162, Country 162",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 162",
    age: 32,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/63.jpg",
    gender: "Female",
    profession: "Profession 163",
    location: "City 163, Country 163",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 163",
    age: 33,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/64.jpg",
    gender: "Male",
    profession: "Profession 164",
    location: "City 164, Country 164",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 164",
    age: 34,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/65.jpg",
    gender: "Female",
    profession: "Profession 165",
    location: "City 165, Country 165",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 165",
    age: 35,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/66.jpg",
    gender: "Male",
    profession: "Profession 166",
    location: "City 166, Country 166",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 166",
    age: 36,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/67.jpg",
    gender: "Female",
    profession: "Profession 167",
    location: "City 167, Country 167",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 167",
    age: 37,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/68.jpg",
    gender: "Male",
    profession: "Profession 168",
    location: "City 168, Country 168",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 168",
    age: 38,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/69.jpg",
    gender: "Female",
    profession: "Profession 169",
    location: "City 169, Country 169",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 169",
    age: 39,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/70.jpg",
    gender: "Male",
    profession: "Profession 170",
    location: "City 170, Country 170",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 170",
    age: 40,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/71.jpg",
    gender: "Female",
    profession: "Profession 171",
    location: "City 171, Country 171",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 171",
    age: 41,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/72.jpg",
    gender: "Male",
    profession: "Profession 172",
    location: "City 172, Country 172",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 172",
    age: 42,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/73.jpg",
    gender: "Female",
    profession: "Profession 173",
    location: "City 173, Country 173",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 173",
    age: 43,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/74.jpg",
    gender: "Male",
    profession: "Profession 174",
    location: "City 174, Country 174",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 174",
    age: 44,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/75.jpg",
    gender: "Female",
    profession: "Profession 175",
    location: "City 175, Country 175",
    countryflag: "https://flagcdn.com/w320/tu.png",
    name: "User 175",
    age: 45,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/76.jpg",
    gender: "Male",
    profession: "Profession 176",
    location: "City 176, Country 176",
    countryflag: "https://flagcdn.com/w320/uv.png",
    name: "User 176",
    age: 46,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/77.jpg",
    gender: "Female",
    profession: "Profession 177",
    location: "City 177, Country 177",
    countryflag: "https://flagcdn.com/w320/vw.png",
    name: "User 177",
    age: 47,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/78.jpg",
    gender: "Male",
    profession: "Profession 178",
    location: "City 178, Country 178",
    countryflag: "https://flagcdn.com/w320/wx.png",
    name: "User 178",
    age: 48,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/79.jpg",
    gender: "Female",
    profession: "Profession 179",
    location: "City 179, Country 179",
    countryflag: "https://flagcdn.com/w320/xy.png",
    name: "User 179",
    age: 49,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/80.jpg",
    gender: "Male",
    profession: "Profession 180",
    location: "City 180, Country 180",
    countryflag: "https://flagcdn.com/w320/yz.png",
    name: "User 180",
    age: 20,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/81.jpg",
    gender: "Female",
    profession: "Profession 181",
    location: "City 181, Country 181",
    countryflag: "https://flagcdn.com/w320/za.png",
    name: "User 181",
    age: 21,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/82.jpg",
    gender: "Male",
    profession: "Profession 182",
    location: "City 182, Country 182",
    countryflag: "https://flagcdn.com/w320/ab.png",
    name: "User 182",
    age: 22,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/83.jpg",
    gender: "Female",
    profession: "Profession 183",
    location: "City 183, Country 183",
    countryflag: "https://flagcdn.com/w320/bc.png",
    name: "User 183",
    age: 23,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/84.jpg",
    gender: "Male",
    profession: "Profession 184",
    location: "City 184, Country 184",
    countryflag: "https://flagcdn.com/w320/cd.png",
    name: "User 184",
    age: 24,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/85.jpg",
    gender: "Female",
    profession: "Profession 185",
    location: "City 185, Country 185",
    countryflag: "https://flagcdn.com/w320/de.png",
    name: "User 185",
    age: 25,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/86.jpg",
    gender: "Male",
    profession: "Profession 186",
    location: "City 186, Country 186",
    countryflag: "https://flagcdn.com/w320/ef.png",
    name: "User 186",
    age: 26,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/87.jpg",
    gender: "Female",
    profession: "Profession 187",
    location: "City 187, Country 187",
    countryflag: "https://flagcdn.com/w320/fg.png",
    name: "User 187",
    age: 27,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/88.jpg",
    gender: "Male",
    profession: "Profession 188",
    location: "City 188, Country 188",
    countryflag: "https://flagcdn.com/w320/gh.png",
    name: "User 188",
    age: 28,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/89.jpg",
    gender: "Female",
    profession: "Profession 189",
    location: "City 189, Country 189",
    countryflag: "https://flagcdn.com/w320/hi.png",
    name: "User 189",
    age: 29,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/90.jpg",
    gender: "Male",
    profession: "Profession 190",
    location: "City 190, Country 190",
    countryflag: "https://flagcdn.com/w320/ij.png",
    name: "User 190",
    age: 30,
    rating: 4.0,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/91.jpg",
    gender: "Female",
    profession: "Profession 191",
    location: "City 191, Country 191",
    countryflag: "https://flagcdn.com/w320/jk.png",
    name: "User 191",
    age: 31,
    rating: 4.1,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/92.jpg",
    gender: "Male",
    profession: "Profession 192",
    location: "City 192, Country 192",
    countryflag: "https://flagcdn.com/w320/kl.png",
    name: "User 192",
    age: 32,
    rating: 4.2,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/93.jpg",
    gender: "Female",
    profession: "Profession 193",
    location: "City 193, Country 193",
    countryflag: "https://flagcdn.com/w320/lm.png",
    name: "User 193",
    age: 33,
    rating: 4.3,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/94.jpg",
    gender: "Male",
    profession: "Profession 194",
    location: "City 194, Country 194",
    countryflag: "https://flagcdn.com/w320/mn.png",
    name: "User 194",
    age: 34,
    rating: 4.4,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/95.jpg",
    gender: "Female",
    profession: "Profession 195",
    location: "City 195, Country 195",
    countryflag: "https://flagcdn.com/w320/no.png",
    name: "User 195",
    age: 35,
    rating: 4.5,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/96.jpg",
    gender: "Male",
    profession: "Profession 196",
    location: "City 196, Country 196",
    countryflag: "https://flagcdn.com/w320/op.png",
    name: "User 196",
    age: 36,
    rating: 4.6,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/97.jpg",
    gender: "Female",
    profession: "Profession 197",
    location: "City 197, Country 197",
    countryflag: "https://flagcdn.com/w320/pq.png",
    name: "User 197",
    age: 37,
    rating: 4.7,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/98.jpg",
    gender: "Male",
    profession: "Profession 198",
    location: "City 198, Country 198",
    countryflag: "https://flagcdn.com/w320/qr.png",
    name: "User 198",
    age: 38,
    rating: 4.8,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/women/99.jpg",
    gender: "Female",
    profession: "Profession 199",
    location: "City 199, Country 199",
    countryflag: "https://flagcdn.com/w320/rs.png",
    name: "User 199",
    age: 39,
    rating: 4.9,
    id: 1,
  },
  {
    img: "https://randomuser.me/api/portraits/men/0.jpg",
    gender: "Male",
    profession: "Profession 200",
    location: "City 200, Country 200",
    countryflag: "https://flagcdn.com/w320/st.png",
    name: "User 200",
    age: 40,
    rating: 4.0,
    id: 1,
  },
];
export const sections = [
  {
    title: "Personal Information",
    data: {
      "My Citizenship": "Pakistani",
      "Country of Origin": "Pakistan",
      "Willing to Relocate?": "Internationally",
      "I am Looking to Marry": "As soon as possible",
      "My Income": "Prefer not to say",
      "Marital Status": "Never married",
      "Would I like to have Children?": "Yes",
      "Do I have children?": "No",
      "My Living Arrangements?": "I Live With Family",
      Country: "Pakistan",
      "County/State": "Gujrat",
      Distance: "213 miles",
    },
  },
  {
    title: "Appearance",
    data: {
      "My Height": "1.55m (5'1\")",
      "My Build": "Slim",
      "My Hair Colour": "Black",
      "Colour of My Eyes": "Brown",
      "Do I Smoke?": "No",
      "Do I Have Any Disabilities?": "No",
    },
  },
  {
    title: "Education",
    data: {
      "My Education Level": "Bachelors degree",
      "Subject I Studied": "Commerce",
    },
  },
  {
    title: "Language",
    data: {
      "My First Language": "Urdu",
      "My Second Language": "Punjabi",
    },
  },
  {
    title: "Work",
    data: {
      "My Profession": "Prefer not to say",
      "My Job Title": "Not working",
    },
  },
  {
    title: "Religion",
    data: {
      Religiousness: "Religious",
      "My Sect": "Sunni",
      "Hijab/Niqab ": "Yes Hijab",
      " Beard": "Yes",
      "Are You a Revert? ": "N0",
      "Do You Keep Halal?": "I Always Keep Halal",
      "Do You Perform Salaah?": "Always",
    },
  },
];
